name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    env:
      ALPACA_API_KEY: dummy
      ALPACA_SECRET_KEY: dummy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy pytest flake8 mypy alpaca-py pydantic
      - name: Lint with flake8
        run: flake8 src tests
      - name: Type-check with mypy
        run: mypy src --ignore-missing-imports
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q